{
    "exp_names": [
        "0"
    ],
    "gen_play_phase_lens": [
        [1, 1],
        [10, 1],
        [10, 10],
        [-1, 10],

        [1, 10],
        [1, 50],
        [10, 50],
        [50, 1],
        [50, 10],
        [50, 50],
        [-1, 1],
        [-1, 50]
    ],
    "qd_objectives": [
        [false, "regret"]
    ],
    "fo_models": [
        [false, "paired"]
    ]
}